---
title: "PanaromaDataAnalysis.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load in libraries

```{r}
library(readr)
library(dplyr)
library(knitr)
library(tidyr)
```

### Prepare the data ###


```{r}
# Importing site-level panorama data

setwd("C:/Users/allison.fox/OneDrive - Palladium International, LLC/Desktop/Technical Work/Anomaly Detection")
filepath <- "C:/Users/allison.fox/OneDrive - Palladium International, LLC/Desktop/Technical Work/Anomaly Detection/"
panorama_raw <- read.csv(paste0(filepath, "SitePerformanceFY2016-FY2021.csv"), stringsAsFactors = FALSE)

```



```{r}
# Select numeric columns of interest
cols_to_keep <- c(2,3,4,5,7:30)
panorama <- panorama_raw[, cols_to_keep]


# filter out entries where facility is N/A
panorama <- panorama %>% filter(Facility != "N/A")

# set "" to N/A
panorama[panorama == ""] <- 0

# rename columns 
panorama <- panorama %>% rename(
  'Country' = Operating.Unit,  
        'Q1Q22015' = X2015.Q1.Q2.R,
          'Q32015' = X2015.Q3.R,
          'Q42015' = X2015.Q4.R,         
          'Q12016' = X2016.Q1.R,
          'Q22016' = X2016.Q2.R,
          'Q32016' = X2016.Q3.R,
          'Q42016' = X2016.Q4.R,
          'Q12017' = X2017.Q1.R,
          'Q22017' = X2017.Q2.R,
          'Q32017' = X2017.Q3.R,
          'Q42017' = X2017.Q4.R,
          'Q12018' = X2018.Q1.R,
          'Q22018' = X2018.Q2.R,
          'Q32018' = X2018.Q3.R,
          'Q42018' = X2018.Q4.R, 
          'Q12019' = X2019.Q1.R,
          'Q22019' = X2019.Q2.R,
          'Q32019' = X2019.Q3.R,
          'Q42019' = X2019.Q4.R,
          'Q12020' = X2020.Q1.R,
          'Q22020' = X2020.Q2.R,
          'Q32020' = X2020.Q3.R,
          'Q42020' = X2020.Q4.R,
          'Q12021' = X2021.Q1.R)

```


# Create list of columns

```{r}
col <- list(colnames(panorama))
columns <- list("Q1Q22015","Q32015","Q42015","Q12016","Q22016","Q32016","Q42016","Q12017",    "Q22017","Q32017","Q42017","Q12018","Q22018","Q32018","Q42018","Q12019","Q22019","Q32019",
"Q42019","Q12020","Q22020","Q32020","Q42020","Q12021")
columns
```


# Data structure transformation

```{r}
str(panorama)
tidy1 <- panorama %>%
  pivot_longer(!Country & !PSNU & !Facility & !Indicator, names_to = "Quarter", values_to = "Count")
```

```{r}
tidy2 <- test_tidy %>%
  pivot_wider(names_from = "Indicator", values_from = "Count")
panorama_processed <- tidy2
```



